data:extend({
    {
        type = "simple-entity-with-owner",
        name = generate_name("lane-balance-main"),
        icon = mod_name .. "/graphics/icons/lane-balancer.png",
        icon_size = 64,
        icon_mipmaps = 4,
        flags = {
            "placeable-neutral",
            "player-creation",
        },
        mining_sound   = nil,
        max_health     = 150,
        selection_box  = { { -0.5, -1.0 }, { 0.5, 1.0 } },
        collision_box  = { { -0.4, -0.8 }, { 0.4, 0.8 } },
        resistances = {
            { type = "fire",   percent = 60 },
            { type = "impact", percent = 30 },
        },
        collision_mask = { "object-layer", "floor-layer", "transport-belt-layer", "water-tile" },
        minable        = { mining_time = 0.1, result = generate_name("lane-balance-main") },
        placeable_by   = { item = generate_name("lane-balance-main"), count = 1 },
        render_layer           = "water-tile",
        secondary_draw_order   = 0,
        picture                = get_1_by_2_picture("lane-balancer", nil),
        fast_replaceable_group = generate_name("lane-balancers"),
        next_upgrade           = generate_name("lane-balance-fast-main"),
    },
    {
        type               = "linked-belt",
        name               = generate_name("lane-balance-real"),
        allow_side_loading = true,
        speed              = base_speed,
        max_health         = 150,
        collision_box      = { { -0.4, -0.4 }, { 0.4, 0.4 } },
        selection_box      = { {  0.0,  0.0 }, { 0.0, 0.0 } },
        resistances = {
            { type = "fire",   percent = 60 },
            { type = "impact", percent = 30 },
        },
        flags = sub_entity_flag,
        working_sound = {
            sound = {
                filename = "__base__/sound/underground-belt.ogg",
                volume   = 0.2
            },
            max_sounds_per_type       = 2,
            audible_distance_modifier = 0.5,
            persistent                = true,
            use_doppler_shift         = false
        },
        structure                   = get_1_by_2_structure("lane-balancer", nil),
        animation_speed_coefficient = 32,
        belt_animation_set          = basic_belt_animation_set,
        fast_replaceable_group      = "linked-belts",
    },
    {
        type = "simple-entity-with-owner",
        name = generate_name("lane-balance-fast-main"),
        icon = mod_name .. "/graphics/icons/fast-lane-balancer.png",
        icon_size = 64,
        icon_mipmaps = 4,
        flags = {
            "placeable-neutral",
            "player-creation",
        },
        mining_sound   = nil,
        max_health     = 160,
        selection_box  = { { -0.5, -1.0 }, { 0.5, 1.0 } },
        collision_box  = { { -0.4, -0.8 }, { 0.4, 0.8 } },
        resistances = {
            { type = "fire",   percent = 60 },
            { type = "impact", percent = 30 },
        },
        collision_mask         = { "object-layer", "floor-layer", "transport-belt-layer", "water-tile" },
        minable                = { mining_time = 0.1, result = generate_name("lane-balance-fast-main") },
        placeable_by           = { item = generate_name("lane-balance-fast-main"), count = 1 },
        render_layer           = "water-tile",
        secondary_draw_order   = 0,
        picture                = get_1_by_2_picture("lane-balancer", "fast"),
        fast_replaceable_group = generate_name("lane-balancers"),
        next_upgrade           = generate_name("lane-balance-express-main"),
    },
    {
        type               = "linked-belt",
        name               = generate_name("lane-balance-fast-real"),
        allow_side_loading = true,
        speed              = base_speed * 2,
        max_health         = 160,
        collision_box      = { { -0.4, -0.4 }, { 0.4, 0.4 } },
        selection_box      = { {  0.0,  0.0 }, { 0.0, 0.0 } },
        resistances = {
            { type = "fire",   percent = 60 },
            { type = "impact", percent = 30 },
        },
        flags = sub_entity_flag,
        working_sound = {
            sound = {
                filename = "__base__/sound/fast-underground-belt.ogg",
                volume = 0.27
            },
            persistent = true
        },
        structure                   = get_1_by_2_structure("lane-balancer", "fast"),
        animation_speed_coefficient = 32,
        belt_animation_set          = fast_belt_animation_set,
        fast_replaceable_group      = "linked-belts",
    },
    {
        type = "simple-entity-with-owner",
        name = generate_name("lane-balance-express-main"),
        icon = mod_name .. "/graphics/icons/express-lane-balancer.png",
        icon_size = 64,
        icon_mipmaps = 4,
        flags = {
            "placeable-neutral",
            "player-creation",
        },
        mining_sound   = nil,
        max_health     = 170,
        selection_box  = { { -0.5, -1.0 }, { 0.5, 1.0 } },
        collision_box  = { { -0.4, -0.8 }, { 0.4, 0.8 } },
        resistances = {
            { type = "fire",   percent = 60 },
            { type = "impact", percent = 30 },
        },
        collision_mask         = { "object-layer", "floor-layer", "transport-belt-layer", "water-tile" },
        minable                = { mining_time = 0.1, result = generate_name("lane-balance-express-main") },
        placeable_by           = { item = generate_name("lane-balance-express-main"), count = 1 },
        render_layer           = "water-tile",
        secondary_draw_order   = 0,
        picture                = get_1_by_2_picture("lane-balancer", "express"),
        fast_replaceable_group = generate_name("lane-balancers"),
    },
    {
        type               = "linked-belt",
        name               = generate_name("lane-balance-express-real"),
        allow_side_loading = true,
        speed              = base_speed * 3,
        max_health         = 170,
        collision_box      = { { -0.4, -0.4 }, { 0.4, 0.4 } },
        selection_box      = { {  0.0,  0.0 }, { 0.0, 0.0 } },
        resistances = {
            { type = "fire",   percent = 60 },
            { type = "impact", percent = 30 },
        },
        flags = sub_entity_flag,
        working_sound = {
            sound = {
                filename = "__base__/sound/express-underground-belt.ogg",
                volume = 0.35
            },
            max_sounds_per_type       = 2,
            audible_distance_modifier = 0.5,
            persistent                = true,
            use_doppler_shift         = false
        },
        structure                   = get_1_by_2_structure("lane-balancer", "express"),
        animation_speed_coefficient = 32,
        belt_animation_set          = express_belt_animation_set,
        fast_replaceable_group      = "linked-belts",
    }
})